apiVersion: v1
kind: Service
metadata:
  name: ingress-zenvault
  namespace: kube-system
spec:
  ports:
#    - port: 80
#      name: http
    - port: 443
      name: https
  selector:
    k8s-app: nginx-ingress-controller
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-vbc
  namespace: kube-system
spec:
  ports:
#    - port: 80
#      name: http
    - port: 443
      name: https
  selector:
    k8s-app: nginx-ingress-controller
  type: LoadBalancer