version: "3"
services:
  mongo:
    image: "davidshue/mongodb:3.4"
    hostname: "vbc-mongo"
    ports:
      - "27017:27017"
      - "28017:28017"
    environment:
      - MONGODB_USER=z9user
      - MONGODB_DATABASE=vbc
      - MONGODB_PASS=password
    networks:
      net:
        aliases:
          - vbc-mongo
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.role == worker]
  kafka:
    image: "spotify/kafka:latest"
    hostname: "vbc-kafka"
    ports:
      - "2181:2181"
      - "9092:9092"
    environment:
      - ADVERTISED_HOST=vbc-kafka
    networks:
      net:
        aliases:
          - vbc-kafka
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.role == worker]
  config:
    image: "davidshue/vbc-config:latest"
    hostname: "vbc-config"
    ports:
      - "8888:8888"
    environment:
      - VBC_PROFILE=swarm
      - JAVA_OPTS=-server -Xms32m -Xmx64m -XX:+UseParallelOldGC
    networks:
      net:
        aliases:
          - vbc-config
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.role == worker]
  server:
    image: "davidshue/vbc-server:latest"
    hostname: "vbc-server"
    ports:
      - "8761:8761"
    depends_on:
      - config
    environment:
      - VBC_PROFILE=swarm
      - JAVA_OPTS=-server -Xms32m -Xmx64m -XX:+UseParallelOldGC
    networks:
      net:
        aliases:
          - vbc-server
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.role == worker]
  gateway:
    image: "davidshue/vbc-gateway:latest"
    hostname: "vbc-gateway"
    ports:
      - "8005:8005"
    depends_on:
      - config
      - server
    environment:
      - VBC_PROFILE=swarm
      - JAVA_OPTS=-server -Xms128m -Xmx256m -XX:+UseParallelOldGC
      - CONFIG_HOST=vbc-config
      - CONFIG_PORT=8888
    networks:
      net:
        aliases:
          - vbc-gateway
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.role == worker]
  node1:
    image: "davidshue/vbc-node:latest"
    hostname: "vbc-node1"
    ports:
      - "8201:8201"
    environment:
      - VBC_PROFILE=node1,swarm
      - JAVA_OPTS=-server -Xms128m -Xmx256m -XX:+UseParallelOldGC
      - CONFIG_HOST=vbc-config
      - CONFIG_PORT=8888
    depends_on:
      - mongo
      - kafka
      - config
      - server
    networks:
      net:
        aliases:
          - vbc-node1
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.role == worker]
  node2:
    image: "davidshue/vbc-node:latest"
    hostname: "vbc-node2"
    ports:
      - "8202:8202"
    environment:
      - VBC_PROFILE=node2,swarm
      - JAVA_OPTS=-server -Xms128m -Xmx256m -XX:+UseParallelOldGC
      - CONFIG_HOST=vbc-config
      - CONFIG_PORT=8888
    depends_on:
      - mongo
      - kafka
      - config
      - server
    networks:
      net:
        aliases:
          - vbc-node2
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.role == worker]
  switch:
    image: "davidshue/vbc-switch:latest"
    hostname: "vbc-switch"
    ports:
      - "7000:7000"
      - "7009:7009"
      - "7443:7443"
    volumes:
      - "/Users/david/workspace/vbc-cloud/switch/src/main/resources/vbc.jks:/etc/zeronines/vbc/vbc.jks:ro"
    depends_on:
      - gateway
    environment:
      - VBC_PROFILE=swarm
      - JAVA_OPTS=-server -Xms128m -Xmx256m -XX:+UseParallelOldGC
      - GATEWAY_HOST=vbc-gateway
      - GATEWAY_PORT=8005
    networks:
      net:
        aliases:
          - vbc-switch
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.role == worker]
networks:
  net:
    ipam:
      config:
        - subnet: 100.128.0.0/16