server:
  port: 7190
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 15

kafka:
  zookeeper: kafka-0.kafka:9093,kafka-1.kafka:9093,kafka-2.kafka:9093
  group:
    prefix: vbc-journal
  autocommit:
    interval: 100
  session:
    timeout: 15000

cassandra:
  endpoints: 127.0.0.1
  keyspace: vbc
journal.blob.enabled: false