apiVersion: v1
kind: Service
metadata:
  name: vbc-gateway
spec:
  selector:
    app: vbc-gateway
  ports:
    -
      port: 8005
      targetPort: 8005
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vbc-gateway
  labels:
    app: vbc-gateway
spec:
  replicas: 1
  template:
    metadata:
      name: vbc-gateway
      labels:
        app: vbc-gateway
    spec:
      containers:
      - name: vbc-gateway
        image: davidshue/vbc-gateway:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: VBC_PROFILE
            value: k8s
          - name: JAVA_OPTS
            value: -server -Xms32m -Xmx64m -XX:+UseParallelOldGC
      restartPolicy: Always
  selector:
    matchLabels:
      app: vbc-gateway
