apiVersion: v1
kind: Service
metadata:
  name: vbc-kafka
  labels:
    name: vbc-kafka
spec:
  selector:
    app: vbc-kafka
  ports:
    - name: zookeeper
      port: 2181
      targetPort: 2181
    - name: kafka
      port: 9092
      targetPort: 9092

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: vbc-kafka
  labels:
    app: vbc-kafka
spec:
  replicas: 1
  template:
    metadata:
      name: vbc-kafka
      labels:
        app: vbc-kafka
    spec:
      containers:
      - name: kafka
        image: spotify/kafka:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: ADVERTISED_HOST
            value: vbc-kafka
      restartPolicy: Always
  selector:
    matchLabels:
      app: vbc-kafka
