apiVersion: v1
kind: Service
metadata:
  name: vbc-config
spec:
  selector:
    app: vbc-config
#  ports:
#    -
#      nodePort: 31888
#      port: 8888
#      targetPort: 8888
#  type: NodePort
  type: LoadBalancer
  ports:
    - port: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vbc-config
  labels:
    app: vbc-config
spec:
  replicas: 1
  template:
    metadata:
      name: vbc-config
      labels:
        app: vbc-config
    spec:
      containers:
      - name: vbc-config
        image: davidshue/vbc-config:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /etc/zeronines/config
            name: vbc-config-volume
        env:
          - name: VBC_PROFILE
            value: native
          - name: JAVA_OPTS
            value: -server -Xms32m -Xmx64m -XX:+UseParallelOldGC
          - name: ENVIRONMENT_ARGS
            value: -Dspring.cloud.config.server.native.searchLocations=/etc/zeronines/config
      restartPolicy: Always
      volumes:
        - name: vbc-config-volume
          configMap:
            name: vbc-config-files
  selector:
    matchLabels:
      app: vbc-config
